config/routes.rb
Rails.application.routes.draw do
  resources :bills
  get '/index' => 'home#index', as: :index
  get 'home/result', as: :result
  post '/loan_status' => 'home#owe_money', as: :owe_money

  root 'home#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  validates :event, :date, :location, :total_amount, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:event, :date, :location, :total_amount, :by_amar, :by_akbar, :by_anthony, :had_to_give_by_amar, :had_to_give_by_akbar, :had_to_give_by_anthony, :missing)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def result

  end
  def owe_money
    @one_month_data = Bill.where(:date => "#{params[:user][:from].gsub('-','/')}".."#{params[:user][:to].gsub('-','/')}")
    @amar = @one_month_data.sum('had_to_give_by_amar')
    @akbar = @one_month_data.sum('had_to_give_by_akbar')
    @anthony = @one_month_data.sum('had_to_give_by_anthony')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bills/_form.html.erb
<div class="container bg-image">
  <%= form_for(@bill) do |f| %>
    <% if @bill.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

        <ul>
        <% @bill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-md-8 col-md-offset-2">
      <div class="col-md-4">
        <div class="field">
          <h6 class="white-font"><%= f.label :event %></h6>
          <%= f.select :event, options_for_select(['Snacks', 'Lunch', 'Dinner']) %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <h6 class="white-font"><%= f.label :date %></h6>
          <%= f.date_select :date %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field">
          <h6 class="white-font"><%= f.label :missing %></h6>
          <%= f.select :missing, options_for_select(['NoOne','Amar', 'Akbar', 'Anthony']) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="field">
          <h6 class="white-font"><%= f.label :location %></h6>
          <%= f.text_field :location %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="field">
          <h6 class="white-font"><%= f.label :total_amount %></h6>
          <%= f.number_field :total_amount %>
        </div>
      </div>
      <div class="col-md-12 grey-bg-color">
        <h4>Paid By</h4>
        <div class="col-md-4 padding-0">
          <div class="field">
            <%= f.label :by_amar %><br>
            <%= f.number_field :by_amar %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="field">
            <%= f.label :by_akbar %><br>
            <%= f.number_field :by_akbar %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="field">
            <%= f.label :by_anthony %><br>
            <%= f.number_field :by_anthony %>
          </div>
        </div>
      </div>
      <div class="field hidden">
        <%= f.label :had_to_give_by_amar %><br>
        <%= f.number_field :had_to_give_by_amar %>
      </div>
      <div class="field hidden">
        <%= f.label :had_to_give_by_akbar %><br>
        <%= f.number_field :had_to_give_by_akbar %>
      </div>
      <div class="field hidden">
        <%= f.label :had_to_give_by_anthony %><br>
        <%= f.number_field :had_to_give_by_anthony %>
      </div>
    </div>
    <div class="col-md-8 col-md-offset-2 margin-top-100 text-center">
      <div class="actions" id="submit_bill">
        <%= f.submit 'Submit'%>
      </div>
    </div>
  <% end %>
</div>

<%=javascript_tag do %>
    $('#bill_missing').click(function() {
    if ($('#bill_missing').val() === 'NoOne') {
    $("#bill_by_amar").prop('disabled', false);
    $("#bill_by_akbar").prop('disabled', false);
    $("#bill_by_anthony").prop('disabled', false);
    }
    if ($('#bill_missing').val() === 'Amar') {
    $("#bill_by_amar").val(0);
    $("#bill_by_amar").prop('disabled', true);
    $("#bill_by_akbar").prop('disabled', false);
    $("#bill_by_anthony").prop('disabled', false);
    }
    if ($('#bill_missing').val() === 'Akbar') {
    $("#bill_by_akbar").val(0);
    $("#bill_by_akbar").prop('disabled', true);
    $("#bill_by_amar").prop('disabled', false);
    $("#bill_by_anthony").prop('disabled', false);
    }
    if ($('#bill_missing').val() === 'Anthony') {
    $("#bill_by_anthony").val(0);
    $("#bill_by_anthony").prop('disabled', true);
    $("#bill_by_amar").prop('disabled', false);
    return $("#bill_by_akbar").prop('disabled', false);
    }
    });

    $('#submit_bill').hover(function() {
    var x;
    x = $('#bill_total_amount').val();
    if ($('#bill_missing').val() === 'NoOne') {
    $('#bill_had_to_give_by_amar').val(($('#bill_by_amar').val()) - Math.round(x / 3));
    $('#bill_had_to_give_by_akbar').val(($('#bill_by_akbar').val()) - Math.round(x / 3));
    return $('#bill_had_to_give_by_anthony').val(($('#bill_by_anthony').val()) - Math.round(x / 3));
    } else {
    if ($('#bill_missing').val() === 'Amar') {
    $('#bill_had_to_give_by_amar').val(0);
    $('#bill_had_to_give_by_akbar').val(($('#bill_by_akbar').val()) - Math.round(x / 2));
    $('#bill_had_to_give_by_anthony').val(($('#bill_by_anthony').val()) - Math.round(x / 2));
    }
    if ($('#bill_missing').val() === 'Akbar') {
    $('#bill_had_to_give_by_amar').val(($('#bill_by_amar').val()) - Math.round(x / 2));
    $('#bill_had_to_give_by_akbar').val(0);
    $('#bill_had_to_give_by_anthony').val(($('#bill_by_anthony').val()) - Math.round(x / 2));
    }
    if ($('#bill_missing').val() === 'Anthony') {
    $('#bill_had_to_give_by_amar').val(($('#bill_by_amar').val()) - Math.round(x / 2));
    $('#bill_had_to_give_by_akbar').val(($('#bill_by_akbar').val()) - Math.round(x / 2));
    return $('#bill_had_to_give_by_anthony').val(0);
    }
    }
    });
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bills</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Date</th>
      <th>Location</th>
      <th>Total amount</th>
      <th>By amar</th>
      <th>By akbar</th>
      <th>By anthony</th>
      <th>Had to give by amar</th>
      <th>Had to give by akbar</th>
      <th>Had to give by anthony</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.event %></td>
        <td><%= bill.date %></td>
        <td><%= bill.location %></td>
        <td><%= bill.total_amount %></td>
        <td><%= bill.by_amar %></td>
        <td><%= bill.by_akbar %></td>
        <td><%= bill.by_anthony %></td>
        <td><%= bill.had_to_give_by_amar %></td>
        <td><%= bill.had_to_give_by_akbar %></td>
        <td><%= bill.had_to_give_by_anthony %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<%= render 'form' %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @bill.event %>
</p>

<p>
  <strong>Date:</strong>
  <%= @bill.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @bill.location %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @bill.total_amount %>
</p>

<p>
  <strong>By amar:</strong>
  <%= @bill.by_amar %>
</p>

<p>
  <strong>By akbar:</strong>
  <%= @bill.by_akbar %>
</p>

<p>
  <strong>By anthony:</strong>
  <%= @bill.by_anthony %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %>

app/views/home/index.html.erb
<div class="container bg-image">
  <div class="col-md-12">
    <div class="col-md-6">
      <a href="bills/new"><button class="float-left"><h1>Pay Bill</h1></button></a>
    </div>
    <div class="col-md-6">
      <a href="home/result"><button class="float-right"><h1>Pay Loan</h1></button></a>
    </div>
  </div>
</div>

app/views/home/owe_money.html.erb
<div class="container bg-image">
  <% @result = 0 %>
  <div class="col-md-12">
    <div class="col-md-6 col-md-offset-4">
      <% if @amar < 0 && @akbar >0 && @anthony > 0%>
        <% @result = 1 %>
        <h2 class='white-font'>Amar has to give <%=@akbar.abs%> rs to Akbar</h2><br>
        <h2 class='white-font'>Amar has to give <%=@anthony.abs%> rs to Anthony</h2><br>
      <%end%>
      <% if @akbar < 0 && @anthony > 0 && @amar > 0%>
        <% @result = 1 %>
        <h2 class='white-font'>Akbar has to give <%=@amar.abs%> rs to Amar</h2><br>
        <h2 class='white-font'>Akbar has to give <%=@anthony.abs%> rs to Anthony</h2><br>
      <%end%>
      <% if @anthony < 0 && @amar > 0 && @akbar >0%>
        <% @result = 1 %>
        <h2 class='white-font'>Anthony has to give <%=@amar.abs%> rs to Amar</h2><br>
        <h2 class='white-font'>Anthony has to give <%=@akbar.abs%> rs to Akbar</h2><br>
      <%end%>
      <% if @amar < 0 && @akbar < 0 %>
        <% @result = 1 %>
        <h2 class='white-font'>Amar has to give <%=@amar.abs%> rs to Anthony</h2><br>
        <h2 class='white-font'>Akbar has to give <%=@akbar.abs%> rs to Anthony</h2><br>
      <%end%>
      <% if @amar < 0 && @anthony < 0 %>
        <% @result = 1 %>
        <h2 class='white-font'>Amar has to give <%=@amar.abs%> rs to Akbar</h2><br>
        <h2 class='white-font'>Anthony has to give <%=@anthony.abs%> rs to Akbar</h2><br>
      <%end%>
      <% if @anthony < 0 && @akbar < 0 %>
        <% @result = 1 %>
        <h2 class='white-font'>Anthony has to give <%=@anthony.abs%> rs to Amar</h2><br>
        <h2 class='white-font'>Akbar has to give <%=@akbar.abs%> rs to Amar</h2><br>
      <%end%>
      <% if @amar == 0 && (@akbar !=0 || @anthony !=0)%>
        <% @result = 1 %>
        <% if @akbar < 0  %>
          <h2 class='white-font'>Akbar has to give <%=@akbar.abs%> rs to Anthony</h2><br>
        <% else %>
          <h2 class='white-font'>Anthony has to give <%=@anthony.abs%> rs to Akbar</h2><br>
        <%end%>
      <%end%>
      <% if @akbar == 0 && (@amar !=0 || @anthony !=0)%>
        <% @result = 1 %>
        <% if @amar < 0  %>
          <h2 class='white-font'>Amar has to give <%=@amar.abs%> rs to Anthony</h2><br>
        <% else %>
          <h2 class='white-font'>Anthony has to give <%=@anthony.abs%> rs to Amar</h2><br>
        <%end%>
      <%end%>
      <% if @anthony == 0 && (@akbar !=0 || @amar !=0)%>
          <% @result = 1 %>
          <% if @amar < 0  %>
              <h2 class='white-font'>Amar has to give <%=@amar.abs%> rs to Akbar</h2><br>
          <% else %>
              <h2 class='white-font'>Anthony has to give <%=@anthony.abs%> rs to Amar</h2><br>
          <%end%>
      <%end%>
      <% if @result == 0 %>
        <h2 class="white-font">No Results Found</h2>
      <%end%>
    </div>
  </div>
</div>

app/views/home/result.html.erb
<div class="container bg-image">
  <%= form_tag owe_money_path, :method => :post do %>
      <div class="col-md-12">
        <div class="col-md-5">
          <h2 class="white-font">From</h2>
          <%= date_field("user", "from", :required => true)%>
        </div>
        <div class="col-md-5">
          <h2 class="white-font">To</h2>
          <%= date_field("user", "to", :required => true) %>
        </div>
        <div class="col-md-2 margin-top-6">
          <h3><%= submit_tag 'Check'%></h3>
        </div>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillSplitting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="jumbotron padding-0">
  <a href="/index"><button>Home</button></a>
  <marquee direction="right"><h4>Bill Splitting</h4></marquee>
</div>

<%= yield %>

</body>
</html>